### PR TITLE
Allow for Dynamic Labels

### LINKED ISSUE #2: Adding `request_path` Causes Preformance Issue
:wave: Recently I forked this library to add `request_path` as one of the items to watch : https://github.com/benfalk/prometheus-plugs/commit/c78bd3ba99f00ff3c226fac4cc3e150318f99973

After putting it through a stress test I notice that the performance gets slower and slower over time.  Bombarding my phoenix application with requests from locust starts with an average response time of ~20ms; however, as the test continues the average continues to grow well into a full second per request.  As soon as I remove the path label I've added in this fork the performance of a load test remains fairly constant through the entire stress test.

I've just started looking into this, if you have any ideas they would be greatly appreciated.

### PR DESCRIPTION
**Pull request by benfalk**
This allows someone to implement the library and add custom labels
without needed to make any further code changes to the library.

@deadtrickster I decided to open a pull request to get the ball rolling on this idea.  I would love to have something like this in as I can see my company wanting different labels I can't even imagine yet.

closes #2

### CODE REVIEW

**Comment by deadtrickster** [comment]
Hey, thank you for PR
Don't you think lines 105 and 107 look suspiciously similar? Maybe line 105 is redundant?

**Comment by benfalk** [comment]
My thought behind it was that it would allow for someone to use the label in the fun if they want or opt not to use it.  I guess however, that they can choose not to use it and match it with an underscore :+1:

**Comment by benfalk** [comment]
I've updated the code, take another peek and let me know what you think :smile:

**Comment by deadtrickster** [comment]
Looks good :+1: 
Could you mention this feature in the module/readme docs with usage snippet (e.g :phoenix_controller).

**Comment by benfalk** [comment]
good idea :+1:

**Comment by benfalk** [comment]
Updated, look good?

**Comment by deadtrickster** [comment]
Yeah, Thank you!

**Comment by deadtrickster** [comment]
@benfalk pushed new version to hex.pm: https://hex.pm/packages/prometheus_plugs

**Comment by benfalk** [comment]
Awesome!

**Pull request merged**
